# Generated by Django 2.2.19 on 2023-09-09 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=7, verbose_name='Цвет в HEX'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Уникальный слаг'),
            preserve_default=False,
        ),
    ]
