# Generated by Django 2.2.19 on 2023-09-18 21:44

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230918_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')], verbose_name='Цвет в HEX'),
        ),
    ]
