# Generated by Django 2.2.19 on 2023-09-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230919_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
    ]
