# Generated by Django 3.2.16 on 2023-09-25 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20230924_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipes/images', verbose_name='Фото рецепта'),
            preserve_default=False,
        ),
    ]
