# Generated by Django 2.2.19 on 2023-09-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230916_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-pk',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
